In [1]:
import numpy as np


In [2]:

# Creating a array with one dimensional
a=np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
# Creating array with buliple rows
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)
# Shape of the array can be seen by using command shape
b.shape

[[1 2 3]
 [4 5 6]
 [7 8 9]]


(3, 3)

In [5]:
# Airthamatic operations

# arithmetic
import numpy
myarray1 = numpy.array([2, 2, 2])
myarray2 = numpy.array([3, 3, 3])
myarray1 + myarray2
myarray1 * myarray2

array([6, 6, 6])

In [6]:
# Boolean operations
a = np.array([100,3,100],float)
a
np.where(a==100,1/a,a)


array([ 0.01,  3.  ,  0.01])

In [11]:
#Sorting
a=np.random.randint(1,100,3)
print(a)
a.sort()
a



[55 99 31]


array([31, 55, 99])

In [12]:

#Creating a random array of multiple rows and columns.
np.random.randint(1,100,(3,4))


array([[75, 44, 92, 79],
       [21, 98,  3, 56],
       [30, 58,  5, 59]])

In [13]:
#Adding and Removing Elements
a=np.array([1,2,3])
print(a)
#np.append(array,values) will append values to end of array.

np.append(a,4)


[1 2 3]


array([1, 2, 3, 4])

In [15]:

#np.insert(array, 3, values)will insert values into array before index 3
np.insert(a,2,6)

array([1, 2, 6, 3])

In [16]:
#np.delete(array, 4, axis=0)will delete row on index 4 of array - single dimensional
np.delete(a,2,axis=0)


array([1, 2])

In [17]:

b=np.array([[1,2,3],[4,5,6],[7,8,9]]) 
print(b)
# Shape of the array can be seen by using command shape
b.shape
np.delete(b,1,axis=1)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 3],
       [4, 6],
       [7, 9]])

In [22]:
#Descriptive Statistics
b=np.array([[1,2,3],[4,5,6],[7,8,9]]) 
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
b.sum()



array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:

b.sum()

45

In [26]:
b.min()

1

In [27]:
b.var()

6.666666666666667

In [28]:
numpy.median(b)

5.0

In [29]:
np.sqrt(b)

array([[ 1.        ,  1.41421356,  1.73205081],
       [ 2.        ,  2.23606798,  2.44948974],
       [ 2.64575131,  2.82842712,  3.        ]])

In [30]:
#sine of each element in the array
np.sin(b)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

In [31]:
# Log of each elemet
np.log(b)

array([[ 0.        ,  0.69314718,  1.09861229],
       [ 1.38629436,  1.60943791,  1.79175947],
       [ 1.94591015,  2.07944154,  2.19722458]])

In [32]:
#absolute value
np.abs(b)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
# Checking equlaity of arrays/Matrix
import numpy
arr1 = numpy.array([2, 2, 2])
arr2 = numpy.array([3, 3, 3])
np.array_equal(arr1,arr2)


False

In [34]:
#Concatenation

import numpy
arr1 = numpy.array([2, 2, 2])
arr2 = numpy.array([3, 3, 3])
np.concatenate((arr1,arr2),axis=0)

array([2, 2, 2, 3, 3, 3])

In [36]:

#Saving all the data in to csv format

import numpy
arr1 = numpy.array([2, 2, 2])
arr2 = numpy.array([3, 3, 3])
arr3=arr1+arr2
type(arr3)
np.savetxt('C:/Users/Sm/Desktop/FDPOU final/data.csv',arr3,delimiter=', ')
